"""Added platform column to User model

Revision ID: 677037227703
Revises: 9521b18ec23d
Create Date: 2024-06-19 11:43:36.147247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677037227703'
down_revision = '9521b18ec23d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.String(), nullable=True))
        batch_op.drop_column('platform_presence')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_presence', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('platform')

    # ### end Alembic commands ###
