"""Initial migration.

Revision ID: 9521b18ec23d
Revises: 
Create Date: 2024-06-19 11:18:42.707137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9521b18ec23d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_presence', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('industry', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('industry')
        batch_op.drop_column('platform_presence')

    # ### end Alembic commands ###
