"""Add sponsor_id column to ad_request table

Revision ID: b2e57b8d234a
Revises: c38900a2cea0
Create Date: 2024-06-22 17:33:12.416027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e57b8d234a'
down_revision = 'c38900a2cea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sponsor_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['sponsor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sponsor_id')

    # ### end Alembic commands ###
